(refactor): Use Nitro web server
movie-web/simple-proxy pull request #12
Opened 2023-09-09 04:19 UTC by zisra

Closes #424

- [x] Use [Nitro](https://nitro.unjs.io/) so you can deploy on any platform
- [x] Deploy buttons for Vercel, Netlify, and CF Workers
- [ ] Check if buttons for Vercel, Netlify, and CF Workers _actually work_
- [ ] Fix redirects not working
- [ ] Implement tests
- [ ] Docker setup

2023-09-09 04:52 UTC, zisra commented
Welp, can't find a way to fix [actions](https://github.com/zisra/simple-proxy/actions/runs/6128985110/job/16636637820#step:6:5)

2023-09-09 08:26 UTC, binaryoverload commented on .github/workflows/cloudflare.yml
> +        node: [ 14 ]
The reason the action might be failing is due to the node version, this is out of date. 18 should be used instead.

2023-09-09 08:56 UTC, binaryoverload commented on routes/index.ts
> +  request.headers.set("Origin", new URL(requestData.destination).origin);
```suggestion

  request.headers.set("Host", new URL(requestData.destination).host);
  request.headers.set("Origin", new URL(requestData.destination).origin);
```

2023-09-09 13:00 UTC, binaryoverload requested changes
When refactoring a codebase, please make sure that you keep the formatting and dev dependencies consistent. 

Please delete all the GitHub actions, we will do them ourselves as it's a bit complicated to setup :)

2023-09-10 09:53 UTC, binaryoverload requested changes
This still does not work on Node.JS - please look at using the [proxyRequest](https://www.jsdocs.io/package/h3#proxyRequest) helper method as discussed.

2023-09-10 12:35 UTC, binaryoverload requested changes

2023-09-10 12:35 UTC, binaryoverload commented on package.json
> +    "eslint-plugin-prettier": "^5.0.0",
This needs to be a dev dependency

2023-09-13 21:10 UTC, mrjvs commented
@binaryoverload can you rereview this?
I took over from this PR, so most code is mine.
The todos in the readme are not in scope for this PR (and im lazy, dont wanna do it)

2023-09-13 21:48 UTC, merged